on: 
  push:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron:  '0 2,5,8,11,14,17,20,23 * * *'

name: R-CMD

jobs:
  R-CMD:
    if: (github.actor == 'henry090')
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} 

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest }

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('dplyr','rmarkdown','devtools','flexdashboard','scales', 'reshape2','janitor'))"
<<<<<<< HEAD
          Rscript -e "install.packages(c('viridis','rgdal','leaflet','rgdal','openxlsx','htmltools','shiny'))"
          Rscript -e "devtools::install_github('jbkunst/highcharter')"
=======
          Rscript -e "install.packages(c('viridis','rgdal','leaflet','rgdal','openxlsx'))"
          Rscript -e "install.packages('highcharter')"
>>>>>>> f39c97fba48349f7840d2283cd4665d537c03034
          
      - name: Render Rmd files from _posts
        run: |
          Rscript rscript.R

      - name: Commit files  
        run: |
          git config --global user.email "turqut.a.314@gmail.com"
          git config --global user.name ${{ github.actor }}
          git add ./docs
          git commit -m "updated site"
          
      - name: Push changes  
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}          
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          

